#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: canaima-bienvenido-gnome
# ARCHIVO: postinst
# DESCRIPCIÓN: Configura el sistema despues la instalación del paquete.
# COPYRIGHT:
#  (C) 2010 Luis Alejandro Martínez Faneyth <martinez.faneyth@gmail.com>
#  (C) 2010 Diego Alberto Aguilera Zambrano <daguilera85@gmail.com>
#  (C) 2010 Carlos Alejandro Guerrero Mora <guerrerocarlos@gmail.com>
#  (C) 2010 Francisco Javier Vásquez Guerrero <franjvasquezg@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

PKG="canaima-bienvenido-gnome"
# Color Verde
VERDE="\e[1;32m"
# Color Rojo
ROJO="\e[1;31m"
# Color Amarillo
AMARILLO="\e[1;33m"
# Negrita
BOLD="\e[1m"
# Caracter de fin de línea
FIN="\e[0m"

function ERROR() {
echo -e ${ROJO}${1}${FIN}
exit 1
}

function ADVERTENCIA() {
echo -e ${AMARILLO}${1}${FIN}
}

function EXITO() {
echo -e ${VERDE}${1}${FIN}
}

case ${1} in

	configure)

	# Para cada usuario en /home/ ...
	for HOME_U in /home/*?; do

		# Obteniendo sólo el nombre del usuario
		USUARIO=$( basename ${HOME_U} )

		# Y en caso de que el usuario sea un usuario activo (existente en /etc/shadow) ...
		if [ $( grep -c "${USUARIO}:.*:.*:.*:.*:.*:::" /etc/shadow ) == 1 ] \
		&& [ $( grep -c "${USUARIO}:.*:.*:.*:.*:.*:/bin/.*sh" /etc/passwd ) == 1 ] \
		&& [ -d ${HOME_U}/.config ] \
		&& [ -d ${HOME_U}/Escritorio ] \
		&& [ -d ${HOME_U} ]; then

			ADVERTENCIA 'Instalando Canaima Bienvenido para el usuario "'${USUARIO}'"'

			# Asegurando que el directorio .config/autostart y .config/canaima-bienvenido-gnome/ estén creados
			mkdir -p /home/${USUARIO}/.config/autostart/
			mkdir -p /home/${USUARIO}/.config/canaima-bienvenido-gnome/
			# con permisos apropiados
			chown ${USUARIO}:${USUARIO} /home/${USUARIO}/.config/autostart/
			chown ${USUARIO}:${USUARIO} /home/${USUARIO}/.config/canaima-bienvenido-gnome/

			# Copiamos el lanzador de escritorio al escritorio de cada usuario
			cp /etc/skel/Escritorio/canaima-bienvenido-gnome.desktop /home/${USUARIO}/Escritorio/
			# con permisos apropiados
			chown ${USUARIO}:${USUARIO} /home/${USUARIO}/Escritorio/canaima-bienvenido-gnome.desktop

			# Copia del archivo de configuración que determina si debe ejecutarse canaima-bienvenido-gnome al inicio o no
			cp /etc/skel/.config/canaima-bienvenido-gnome/usuario.conf /home/${USUARIO}/.config/canaima-bienvenido-gnome/
			# con permisos apropiados
			chown ${USUARIO}:${USUARIO} /home/${USUARIO}/.config/canaima-bienvenido-gnome/usuario.conf

			# Copia del lanzador automático de canaima-bienvenido-gnome a cada usuario
			cp /etc/skel/.config/autostart/canaima-bienvenido-gnome-automatico.desktop /home/${USUARIO}/.config/autostart/
			# con permisos apropiados
			chown ${USUARIO}:${USUARIO} /home/${USUARIO}/.config/autostart/canaima-bienvenido-gnome-automatico.desktop
		fi
	done

	;;

        abort-upgrade|abort-remove|abort-deconfigure)
        ;;

        *)

		ERROR "postinst no reconoce el argumento '"${1}"'" >&2
                exit 1

        ;;

esac

#DEBHELPER#

exit 0
