#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: canaima-bienvenido
# ARCHIVO: preinst
# DESCRIPCIÓN: Configura el sistema antes de la instalación del paquete.
# COPYRIGHT:
#  (C) 2010 Luis Alejandro Martínez Faneyth <martinez.faneyth@gmail.com>
#  (C) 2010 Diego Alberto Aguilera Zambrano <daguilera85@gmail.com>
#  (C) 2010 Carlos Alejandro Guerrero Mora <guerrerocarlos@gmail.com>
#  (C) 2010 Francisco Javier Vásquez Guerrero <franjvasquezg@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

PKG="canaima-bienvenido"

case ${1} in

	install|upgrade)

                # ¿Existe un enlace simbólico llamado Desktop?
                # ¿Y una carpeta llamada Escritorio?
                if [ -h /etc/skel/Desktop ] && [ -d /etc/skel/Escritorio ]
                then

                        # Borra el enlace simbólico
                        rm -f /etc/skel/Desktop

                # ¿Existe un enlace simbólico llamado Escritorio?
                # ¿Y una carpeta llamada Desktop?
                elif [ -h /etc/skel/Escritorio ] && [ -d /etc/skel/Desktop ]
                then

                        # Borra el enlace simbólico
                        rm -f /etc/skel/Escritorio

                        # y renombra la carpeta a Escritorio
                        mv /etc/skel/Desktop /etc/skel/Escritorio

                fi

		if [ -e /etc/skel/Escritorio/Bienvenido\ a\ Canaima.desktop ]
		then

			rm -f /etc/skel/Escritorio/Bienvenido\ a\ Canaima.desktop

		fi

                if [ -e /etc/skel/.config/autostart/Bienvenido\ a\ Canaima.desktop ]
                then

                        rm -f /etc/skel/.config/autostart/Bienvenido\ a\ Canaima.desktop
                
                fi

		# Para cada usuario en /home/ ...
		for usuario in /home/*? ;
		do

		# ¿Existe un enlace simbólico llamado Desktop?
		# ¿Y una carpeta llamada Escritorio?
		if [ -h ${usuario}/Desktop ] && [ -d ${usuario}/Escritorio ]
		then

			# Borra el enlace simbólico
        	        rm -f ${usuario}/Desktop

		# ¿Existe un enlace simbólico llamado Escritorio?
		# ¿Y una carpeta llamada Desktop?
		elif [ -h ${usuario}/Escritorio ] && [ -d ${usuario}/Desktop ]
		then

			# Borra el enlace simbólico
			rm -f ${usuario}/Escritorio

			# y renombra la carpeta a Escritorio
			mv ${usuario}/Desktop ${usuario}/Escritorio

		fi

                if [ -e ${usuario}/.config/autostart/Bienvenido\ a\ Canaima.desktop ]
                then

                        rm -f ${usuario}/.config/autostart/Bienvenido\ a\ Canaima.desktop
                
                fi

                if [ -e ${usuario}/Escritorio/Bienvenido\ a\ Canaima.desktop ]
                then

                        rm -f ${usuario}/Escritorio/Bienvenido\ a\ Canaima.desktop

                fi

		# Configuremos XDG para que use como locale "es_VE" y
		# Escritorio como carpeta de usuario predeterminada

		echo "es_VE" > ${usuario}/.config/user-dirs.locale

		sed -i 's/$HOME\/Desktop/$HOME\/Escritorio/g' ${usuario}/.config/user-dirs.dirs

		# Actualicemos la configuración
		xdg-user-dirs-update

		done

	;;

        abort-upgrade)
        ;;

        *)
                echo "preinst no reconoce el argumento '"${1}"'" >&2
                exit 1
        ;;

esac

#DEBHELPER#

exit 0
