#!/bin/bash -e

case ${1} in
	install|configure)

	#Para cada usuario en /home/ ...
	for usuario in /home/*? ;
	do

	if [ -h ${usuario}/Desktop ] && [ -d ${usuario}/Escritorio ]
	then

                rm ${usuario}/Desktop

	elif [ -h ${usuario}/Escritorio ] && [ -d ${usuario}/Desktop ]
	then
	
		rm ${usuario}/Escritorio
		mv ${usuario}/Desktop ${usuario}/Escritorio

	fi

	echo "es_VE" > ${usuario}/.config/user-dirs.locale
	sed -i 's/$HOME\/Desktop/$HOME\/Escritorio/g' ${usuario}/.config/user-dirs.dirs

	xdg-user-dirs-update

	done

	;;
esac

#DEBHELPER#
